# 

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [7]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})

In [8]:
df2 = pd.DataFrame({"key": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [9]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [10]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [11]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [12]:
pd.merge(df1, df2,on="key")

key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [13]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})

In [14]:
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [15]:
pd.merge(df3, df4, left_on="lkey", right_on="rkey")

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [16]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [17]:
pd.merge(df1, df2, how="outer")

key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [18]:
pd.merge(df3, df4, left_on="lkey", right_on="rkey", how="outer")

lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In [20]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": pd.Series(range(6), dtype="Int64")})

In [21]:
df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                    "data2": pd.Series(range(5), dtype="Int64")})

In [22]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [23]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [25]:
pd.merge(df1, df2, how="inner")

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [26]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                     "key2": ["one", "two", "one"],
                     "lval": pd.Series([1, 2, 3],dtype="Int64")})

In [27]:
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                     "key2": ["one",  "one", "one", "two",],
                     "lval": pd.Series([4, 5, 6, 7],dtype="Int64")})

In [28]:
pd.merge(left, right, on=["key1", "key2"], how="outer")

key1 key2  lval_x  lval_y
0  bar  one       3       6
1  bar  two    <NA>       7
2  foo  one       1       4
3  foo  one       1       5
4  foo  two       2    <NA>

In [29]:
pd.merge(left, right, on="key1")

key1 key2_x  lval_x key2_y  lval_y
0  foo    one       1    one       4
1  foo    one       1    one       5
2  foo    two       2    one       4
3  foo    two       2    one       5
4  bar    one       3    one       6
5  bar    one       3    two       7

In [30]:
left1 = pd.DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
                    "value": pd.Series(range(6), dtype="Int64")})

In [31]:
right1 = pd.DataFrame({"group_val": [3.5, 7]}, index=["a", "b"])

In [32]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [33]:
right1

group_val
a        3.5
b        7.0

In [34]:
pd.merge(left1, right1, left_on="key", right_index=True)

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [38]:
lefth = pd.DataFrame({"key1":["Ohio", "Ohio", "Ohio",
                              "Nevaba", "Nevaba"],
                      "key2":[2000, 2001, 2002, 2001, 2002],
                      "data": pd.Series(range(5), dtype="Int64")})

In [39]:
right_index = pd.MultiIndex.from_arrays(
    [
        ["Nevaba", "Nevaba", "Ohio", "Ohio", "Ohio", "Ohio"],
        [2001, 2000, 2000, 2000, 2001, 2002]
    ]
)

In [40]:
right = pd.DataFrame({"event1": pd.Series([0, 2, 4, 6, 8, 10], dtype="Int64",
                                          index=right_index),
                      "event2": pd.Series([1, 3, 5, 7, 9, 11], dtype="Int64",
                                          index=right_index)})

In [41]:
lefth

key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevaba  2001     3
4  Nevaba  2002     4

In [42]:
right

event1  event2
Nevaba 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [43]:
pd.merge(lefth, right, left_on=["key1", "key2"], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11
3  Nevaba  2001     3       0       1

In [44]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                     index=["a", "c", "e"],
                     columns=["Ohio", "Nevada"]).astype("Int64")

In [45]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                      index=["b", "c", "d", "e"],
                      columns=["Missouri", "Alabama"]).astype("Int64")

In [50]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [51]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [53]:
pd.merge(left2, right2, how="outer", left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [54]:
left2.join(right2, how="outer")

Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [55]:
left1.join(right1, on="key")

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [56]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                       index=["a", "c", "e", "f"],
                       columns=["New York", "Oregon"])

In [59]:
another

New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [61]:
left2.join([right2, another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0

In [62]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [63]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [66]:
left2.join([right2, another], how="outer")

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0
b  <NA>    <NA>         7        8       NaN     NaN
d  <NA>    <NA>        11       12       NaN     NaN
f  <NA>    <NA>      <NA>     <NA>      16.0    17.0

In [68]:
arr = np.arange(12).reshape((3, 4))

In [69]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [72]:
s1 = pd.Series([0, 1], index=["a", "b"], dtype="Int64")
s2 = pd.Series([2, 3, 4], index=["c", "d", "e"], dtype="Int64")
s3 = pd.Series([5, 6], index=["f", "g"], dtype="Int64")

In [73]:
s1

a    0
b    1
dtype: Int64

In [74]:
s2

c    2
d    3
e    4
dtype: Int64

In [75]:
s3

f    5
g    6
dtype: Int64

In [76]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [77]:
pd.concat([s1, s2, s3], axis="columns")

0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [78]:
s4 = pd.concat([s1, s3])

In [79]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [80]:
pd.concat([s1, s4], axis="columns")

0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [81]:
pd.concat([s1, s4], axis="columns", join="inner")

0  1
a  0  0
b  1  1

In [82]:
result = pd.concat([s1, s2, s3], keys=["one", "two", "three"])

In [83]:
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: Int64

In [84]:
result.unstack()

a     b     c     d     e     f     g
one       0     1  <NA>  <NA>  <NA>  <NA>  <NA>
two    <NA>  <NA>     2     3     4  <NA>  <NA>
three  <NA>  <NA>  <NA>  <NA>  <NA>     5     6

In [85]:
pd.concat([s1, s2, s3], axis="columns", keys=["one", "two", "three"])

one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [87]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=["a", "b", "c"],
                   columns=["one", "two"])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=["a", "c"],
                   columns=["three", "four"])

In [88]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [89]:
df2

three  four
a      5     6
c      7     8

In [91]:
pd.concat([df1, df2], axis="columns", keys=["level1", "level2"])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [92]:
pd.concat([df1, df2], keys=["level1", "level2"])

one  two  three  four
level1 a  0.0  1.0    NaN   NaN
       b  2.0  3.0    NaN   NaN
       c  4.0  5.0    NaN   NaN
level2 a  NaN  NaN    5.0   6.0
       c  NaN  NaN    7.0   8.0

In [93]:
pd.concat({"level1": df1, "level2":df2}, axis="columns")

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [95]:
pd.concat([df1, df2], axis="columns", keys=["level1", "level2"],
          names=["upper", "lower"])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [96]:
df1 = pd.DataFrame(np.random.standard_normal((3, 4)),
                   columns=["a", "b", "c", "d"])

In [99]:
df2 = pd.DataFrame(np.random.standard_normal((2, 3)),
                   columns=["b", "d", "a"])

In [100]:
df1

a         b         c         d
0 -0.036753 -2.109863  0.464637 -2.193601
1 -0.766943 -0.684367  1.013805 -0.075990
2  0.224303  1.553314 -0.534988  0.294867

In [101]:
df2

b         d         a
0 -1.242023  1.324994 -0.325766
1 -0.598095  0.672570 -0.529070

In [102]:
pd.concat([df1, df2], ignore_index=True)

a         b         c         d
0 -0.036753 -2.109863  0.464637 -2.193601
1 -0.766943 -0.684367  1.013805 -0.075990
2  0.224303  1.553314 -0.534988  0.294867
3 -0.325766 -1.242023       NaN  1.324994
4 -0.529070 -0.598095       NaN  0.672570

In [103]:
a = pd.Series([np.nan, 2.5, 0.0, 3.5, 4.5, np.nan],
              index=["f", "e", "d", "c", "b", "a"])

In [105]:
b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
              index=["a", "b", "c", "d", "e", "f"])

In [106]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [107]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [108]:
np.where(pd.isna(a), b, a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [110]:
df1 = pd.DataFrame({"a": [1., np.nan, 5., np.nan],
                    "b": [np.nan, 2., np.nan, 6.],
                    "c": range(2, 18, 4)})

In [111]:
df2 = pd.DataFrame({"a": [5., 4., np.nan, 3., 7.],
                    "b": [np.nan, 3., 4., 6., 8.]})

In [112]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [113]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [114]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN